export const FINANCIAL_CATEGORIES = [
  {
    id: 'ALIMENTACION',
    name: 'Alimentación',
    icon: '🥑',
    color: '#10b981',
    type: 'EXPENSE',
    subCategories: ['Supermercado', 'Restaurantes & Cenas', 'Cafeterías', 'Delivery & Comida Rápida'],
  },
  {
    id: 'VIVIENDA',
    name: 'Vivienda & Servicios',
    icon: '🏠',
    color: '#38bdf8',
    type: 'EXPENSE',
    subCategories: ['Alquiler / Hipoteca', 'Electricidad & Gas', 'Agua', 'Internet & Fibra', 'Mantenimiento & Hogar'],
  },
  {
    id: 'TRANSPORTE',
    name: 'Transporte & Movilidad',
    icon: '🚗',
    color: '#f59e0b',
    type: 'EXPENSE',
    subCategories: ['Combustible', 'Transporte Público', 'Taxi / Uber / VTC', 'Mantenimiento Vehículo', 'Peajes & Parking'],
  },
  {
    id: 'SOFTWARE_TECH',
    name: 'Software & Cloud',
    icon: '💻',
    color: '#a855f7',
    type: 'EXPENSE',
    subCategories: ['Servidores & Cloud', 'Suscripciones Software (SaaS)', 'Hardware & Periféricos', 'Dominios & Hosting'],
  },
  {
    id: 'SALUD',
    name: 'Salud & Bienestar',
    icon: '🩺',
    color: '#ec4899',
    type: 'EXPENSE',
    subCategories: ['Farmacia & Medicamentos', 'Consultas Médicas', 'Gimnasio & Deporte', 'Seguro de Salud'],
  },
  {
    id: 'OCIO_VIAJES',
    name: 'Ocio & Cultura',
    icon: '🎭',
    color: '#e2c275',
    type: 'EXPENSE',
    subCategories: ['Viajes & Hoteles', 'Streaming & Entretenimiento', 'Cine & Eventos', 'Ropa & Estilo'],
  },
  {
    id: 'INGRESOS_PRO',
    name: 'Ingresos Profesionales',
    icon: '💼',
    color: '#10b981',
    type: 'INCOME',
    subCategories: ['Nómina / Salario', 'Consultoría & Servicios', 'Dividendos & Rendimientos', 'Venta de Activos', 'Ingresos Extra'],
  },
  {
    id: 'INVERSION_AHORRO',
    name: 'Inversión & Ahorro',
    icon: '📈',
    color: '#e2c275',
    type: 'TRANSFER',
    subCategories: ['Fondos Indexados', 'Fondo de Emergencia', 'Bienes Raíces', 'Criptoactivos', 'Planes de Pensiones'],
  },
];

export const POPULAR_TAGS = [
  '#Trabajo',
  '#Deducible',
  '#Vacaciones',
  '#Fijo',
  '#Discrecional',
  '#FIRE',
  '#Ahorro',
  '#Familia',
  '#Saludable',
  '#Urgente',
];
